name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Configure machine
      run: |
        apt-get update -qq
        apt-get install ninja-build cmake g++-10 clang

    - name: Configure build
      run: |
        mkdir build.tmp && cd build.tmp
        cmake .. -G ninja-build -DSKIP_BUILD_TEST=ON

    - name: Perform build
      run: ninja
